### ISSUE TITLE
Debito técnico da remoção de serviços pagos 

### ISSUE THREAD

**Issue by Bouckaert** [Openredu/Openredu#119]
Pull request https://github.com/Openredu/Openredu/pull/115 foi adicionado ao código antes das devidas correções.

    Ocorrências não removidas:
    chat:
    app/assets/stylesheets/print.css
    app/assets/stylesheets/landing.scss
    app/assets/stylesheets/landing/_social-network-n-chat.scss
    app/views/landing/_functionalities.html.erb
    app/views/landing/_social_network_n_chat.html.erb
    lib/assets/stylesheets/bootstrap-redu.scss

```
Zencoder:
app/models/seminar.rb (Apenas comentado, melhor remover )
Já que não faremos conversão nem player embedado, não seria melhor remover também o jwplayer?

S3:
Gemfile
public/maintenance.html
lib/storage.rb
config/schedule.rb
Gemfile.lock
recipes/cookbooks/main/recipes/default.rb
recipes/cookbooks/s3cmd/
app/models/seminar.rb
```

    Seria melhor dar o lock da gem num branch de hotfix:
    +gem "mysql2", '0.3.17'

    Verificar se a biblioteca easyXDM.js era usada apenas pelo chat

    app/models/seminar.rb
    (Apenas comentado, é melhor apagar o método inteiro)

    app/views/friendships/create.js.erb
    <% if > ficou com cláusula vazia, melhor remover.

    app/views/lectures/admin/_seminar_fields.html.erb
    Apenas comentado, melhor remover
    +

    config/application.rb

Melhoria:
config.paperclip = {
…

    :path => File.join(Rails.root.to_s, "public/images/:class/:attachment/:id/:style/:basename.:extension")
    Salvar em diretório externo a aplicação

    config.video_transcoded = {
    Não seria melhor remover já que não haverá transcode?

    config/environments/performance.rb

    #config.action_mailer.asset_host = config.action_controller.asset_host
    Apenas comentado, melhor remover.

**Comment by rafaellsma** [comment]
As ocorrências de chat a maioria estão relacionadas com a landing page, a qual precisaria ser reposicionada. Outras ocorrências estão relacionadas aos icones de chat do bootstrap do Openredu.

![image](https://cloud.githubusercontent.com/assets/13156606/25969185/6e8f300c-366a-11e7-8bc2-038f83136d6c.png)

Ao remover o método zencoder percebi que precisamos refatorar a classe toda Seminar, pois existe muita coisa desnecessária para sua atual funcionalidade.

Quem usa a easyXDM é o canvas.

Toda a remoção do video foi pensando em futuramente reativar, então precisamos refatorar toda a classe Seminar.
