### ISSUE TITLE
Remoção do scribd

### ISSUE THREAD

**Issue by rafaellsma** [Openredu/Openredu#143]
- Investigar se o serviço parou para sempre.
- Pr com o livredoc já está pronto
- Remover o scribd do código

**Comment by Bouckaert** [comment]
Só pra complementar:

Remover 43 ocorrências esquecidas do scribd em:
 
Gemfile
config/scribd_fu.yml
Gemfile.lock
spec/controllers/lectures_controller_spec.rb
spec/requests/api/lectures/document_spec.rb
spec/support/scribd.rb
spec/models/document_spec.rb
spec/models/quota_spec.rb
spec/models/ability_spec.rb
spec/spec_helper.rb
app/representers/api/document_representer.rb
app/models/subject.rb
app/models/document.rb
 
Remover 12 ocorrências esquecidas do scribd(ipaper) em:
 
spec/models/document_spec.rb:
app/models/document.rb
app/views/lectures/_document.html.erb
Remover ‘ipaper_id’ e ‘ipaper_access_key’ de documents
