### ISSUE TITLE
Dúvidas sobre o PagSeguro

### ISSUE THREAD

**Issue by paulolieuthier** [Openredu/Openredu#17]
Eu vi que o PagSeguro é usado nas inscrições dos planos pelos professores. É usado em mais algum lugar? Se os planos pagos serão removidos, apenas o plano gratuito já existente continuará, ou haverá outros? Quais serão as características (quantidade de alunos, espaço de armazenamento...)?

E em relação às empresas e instituições, como funcionará? Como o OpenRedu não é um serviço, mas uma aplicação, faz mais sentido isto também ser removido. Certo?

cc @miguelarauj1o

**Comment by miguelarauj1o** [comment]
@Bouckaert

**Comment by JoaoGFarias** [comment]
@Bouckaert poderias marcar essa issue com a label Discussão?

**Comment by Bouckaert** [comment]
O PagSeguro é utilizado apenas na criação dos cursos. O objetivo é modularizar a funcionalidade de cobrança para atendermos a duas realidades:

R1 - Instituições que não possuem interesse em cobrar pelo uso da plataforma;
R2 - Instituições interessadas em cobrar pelo uso da plataforma;

Minha sugestão é removermos do core o PagSeguro e implementar uma tela de administração do ambiente, onde o responsável pela instância possa configurar as permissões do curso (Quantidade de alunos, espaço de armazenamento...) atendendo a R1.

A feature de pagamento removida do core seria modularizada para atender a R2.

@paulolieuthier @miguelarauj1o Vocês poderiam ficar responsáveis pela remoção do Pagseguro do Core e criação do módulo(Gem?) de cobrança, back-end.

@caiocaladoo Tua equipe pode ficar responsável pela criação das telas de administração do ambiente(core) e cobrança(módulo), front-end.

Referência(front-end):
http://developers.redu.com.br/ui-components/
[G.U.I. (1.3.9a).pdf](https://github.com/OpenRedu/OpenRedu/files/31951/G.U.I.1.3.9a.pdf)

**Comment by miguelarauj1o** [comment]
_"Yves, eu e Miguel estamos atrasados, e estamos confusos com o projeto. Eu não entendi bem a resposta de Alex, e estou sem saber o que fazer. Eu removi a tela de escolha do plano (quando clica em ensine), como Alex falou uma vez. Mas é pra tirar mesmo? Ou pra mudar as opções? A instituição que rodar o seu OpenRedu vai cobrar de professores (como é atualmente), ou cobrar dos alunos? Tu poderia explicar melhor os nossos próximos passos?"_

@Bouckaert 
_"Então, é pra tirar mesmo...
Acredito que as instituições devem querer cobrar dos alunos...
O proximo passo acredito que seria criar uma tela de administração do ambiente. Onde o admin poderia setar as permissões (uso de disco, número de alunos, professores...) dos ambientes.
Feito isso acho que vocês podem partir para modularização do pagamento para os alunos."_

__cc__ @paulolieuthier

**Comment by miguelarauj1o** [comment]
Relatório sobre a situação atual do [desafio 4](https://docs.google.com/viewer?a=v&pid=sites&srcid=Y2luLnVmcGUuYnJ8ZXNlfGd4OjIwMzRlZjRlZDQ1YjA5NDM):
[[IF800] Relatório-2.pdf](https://github.com/OpenRedu/OpenRedu/files/67068/IF800.Relatorio-2.pdf)

__cc__ @alexodrosgomes @fernandocastor @Bouckaert @paulolieuthier

**Comment by leandromarquesrr** [comment]
@tiagonog , podemos fechar essa issue? pagseguro foi removido!
