### ISSUE TITLE
Correções na Wiki do projeto

### ISSUE THREAD

**Issue by miguelarauj1o** [OpenRedu/OpenRedu#18]
Olá, segue abaixo algumas correções na wiki (especificamente na seção [Redu Setup](https://github.com/OpenRedu/OpenRedu/wiki/Redu-Setup)):

No subtópico 1. ii. MAC OS X:

Em "Se sua versão for diferente do Ruby 1.9.3, instale a versão 1.9.3 do Ruby:"
~~$ rvm install ruby 1.9.3~~
```$ rvm install ruby 1.9.3-p551```

_obs.: eu fiz o setup do projeto em duas máquina, além da minha, e sempre que eu tentava instalar esta versão do ruby, ele retornava um erro e informava para instalar a outra._

Em "5) Instalar o MySQL"
~~$ brew install mysql-client mysql-server libmysqlclient-dev~~
```brew install mysql```

_obs.: o homebrew não encontra estas fórmulas, mas existe uma fórmula mysql. Eu instalei ela e consegui levantar o ambiente. Então eu SUPONHO que ela engloba as citadas acima._

Em "10) Problemas com o Ghostscript no Mac"
~~brew update~~

_obs.: este passo já é feito momentos antes, tornando-o desnecessário_

Em "Finalmente baixando o código"
~~$ git clone git@github.com:redu/redu.git~~
```$ git clone git@github.com:OpenRedu/OpenRedu.git```

Em "Criar arquivo database.yml"
> Inicialmente você deve criar uma base de dados para o Redu. Em seguida, escrever o database.yml, segundo as configurações do seu Banco de Dados. O arquivo database.yml.example, localizado na pasta redu/config, pode ser usado como base. Copie-o, e renomeie para database.yml. Caso esteja usando o usuário root do MySQL, basta adicionar a senha deste nos campos password.

trocar por:
> Inicialmente você deve criar uma base de dados para o Redu. Em seguida, escrever o database.yml, segundo as configurações do seu Banco de Dados. O arquivo database.yml.example, localizado na pasta redu/config, pode ser usado como base. Caso esteja usando o usuário root do MySQL, basta adicionar a senha deste nos campos password. Portanto: 
Abra o console e vá para a pasta do projeto.
Renomeie o arquivo _config/database.yml.example_ por _config/database.yml_

_obs.: sugestão_

Em "Instalando Gems necessários ao Redu", para evitar erros de conflito de versões, pode ser necessário prefixar ao comando `rake` o comando `bundle exec`. Por exemplo:
```
$ rake sunspot:solr:start
rake aborted!
Gem::LoadError: You have already activated rake 10.4.2, but your Gemfile requires rake 10.0.4.
$ bundle exec rake sunspot:solr:start
// success
```

cc @paulolieuthier

**Comment by JoaoGFarias** [comment]
Estou criando um shell script para automatizar o processo de setup.

Você podem encontrá-lo - e colaborar - [neste link](https://gist.github.com/JoaoGFarias/b00c8a527599cbdfb5c9)

[Aparentemente](http://stackoverflow.com/questions/4050798/github-is-it-possible-to-collaborate-with-someone-on-a-private-gist), não é possível editar diretamente o gist; vocês podem colocar as contribuições nos comentários e eu vou atualizando. o/

[]s
João

**Comment by miguelarauj1o** [comment]
Porque não manda um pr logo?
Acredito que seria interessante deixar direto no projeto.

**Comment by JoaoGFarias** [comment]
Ainda em desenvolvimento - por enquanto, só cobre 3 dos 9 passos.
É melhor deixar o desenvolvimento disso centralizado no gist, assim não tem re-trabalho e qualquer erro é rapidamente detectado; quando estiver completo, faço um PR.

**Comment by JoaoGFarias** [comment]
Um problema que tive foi na instalação do MySQL.
A versão atual (5.7.9) gera um erro quando a gem mysql2 é usada.
[Há uma issue](https://github.com/brianmario/mysql2/issues/548) no repositório do mysql2 que diz que esse problema foi resolvido - Com um "hack" (gambiarra mesmo), vide [esta linha](https://github.com/sodabrew/mysql2/blob/6822ad6aad46a64fe37e65dbede94d7d552bb7d7/ext/mysql2/client.c#L1382).

Fiz o downgrade para o MySQL 5.6 e tudo roda ok. Gostaria que alguém confirmasse isso para eu alterar a página de setup.

**Comment by embs** [comment]
@miguelarauj1o 

pelo que vi aqui, todas as sugestões já foram adicionadas à wiki, correto? Vou fechar o issue, qqr coisa diz aí.

---

> Estou criando um shell script para automatizar o processo de setup.

@JoaoGFarias, criei um issue específico pra discutirmos isso. #22

---

> Um problema que tive foi na instalação do MySQL.

@JoaoGFarias, podes abrir um issue específico pra esse problema?

**Comment by miguelarauj1o** [comment]
@embs, correto. :+1:
