### ISSUE TITLE
Duplicação em categorias em "Gerenciar Curso"

### ISSUE THREAD

**Issue by jctvEC** [Openredu/Openredu#182]
Estou fazendo um curso, e quando fui selecionar as categorias destinadas ao curso, as mesmas estavam duplicadas.
![captura de tela 2017-08-30 as 09 44 25](https://user-images.githubusercontent.com/26723995/29872965-1b1e5876-8d68-11e7-988e-ccd18ac009bd.png)
![captura de tela 2017-08-30 as 09 44 30](https://user-images.githubusercontent.com/26723995/29872964-1b1da2be-8d68-11e7-882f-33cb3c069f00.png)

**Comment by heitorado** [comment]
Fixed ;)
