### ISSUE TITLE
Specs falhando no branch master

### ISSUE THREAD

**Issue by JoaoGFarias** [Openredu/Openredu#19]
Em anexo encontra-se o resultado da execução dos testes Rspec do commit 473b202 - Branch Master
- Foram 3400 testes executados:
  - 160 passaram
  - 3165 falhas.
  - 75 ficaram pendentes.

<img width="470" alt="screen shot 2015-11-17 at 8 06 16 pm" src="https://cloud.githubusercontent.com/assets/1585655/11227776/f7c8864c-8d66-11e5-978a-f2dbe0c02693.png">

[Rspec Results]()

**Comment by JoaoGFarias** [comment]
Todos os testes que falharam falam em sua mensagem de erro que alguma tabela de teste não existe (redu_test.environments, redu_test.users, etc, etc).

Estes testes estão depreciados ou cometi algum erro de setup do ambiente?

**Comment by embs** [comment]
Compartilha o trace dos testes, por favor, @JoaoGFarias.

Quais foram os comandos que vc usou pra fazer o setup do projeto?

**Comment by JoaoGFarias** [comment]
Como o GitHub não aceita .html ou .zip, estou colocando os resultados no Dropbox, neste link: https://www.dropbox.com/s/o3nu0fa057bj8vg/rspec_results.html?dl=0

Abaixo, um snapshot do início desses resultados:

<img width="1014" alt="screen shot 2015-11-19 at 8 02 54 pm" src="https://cloud.githubusercontent.com/assets/1585655/11287190/9c67ffb0-8ef8-11e5-90c6-93cd476c51de.png">

**Comment by embs** [comment]
.html ou .zip? :eyes: 

Você não está usando a linha de comando?

**Comment by embs** [comment]
> No momento que executei esse comando, o OpenRedu estava rodando em localhost, seguindo o procedimento da página de setup

@JoaoGFarias, vc quis dizer que o servidor da aplicação estava rodando em localhost durante a execução dos testes? Há alguma dependência entre o ambiente de desenvolvimento e o de testes?

**Comment by JoaoGFarias** [comment]
>.html ou .zip? :eyes:
>Você não está usando a linha de comando?

Não posso fazer upload em nenhum dos dois formatos; por isso coloquei os resultados (.html) no [Dropbox](https://www.dropbox.com/s/o3nu0fa057bj8vg/rspec_results.html?dl=0).
E estou usando a linha de comando; passei o comando acima.


>@JoaoGFarias, vc quis dizer que o servidor da aplicação estava rodando em localhost durante a >execução dos testes? Há alguma dependência entre o ambiente de desenvolvimento e o de testes?

Sim, o servidor estava rodando em localhost.
Sobre as dependências, eu não sei. Não vi na documentação nenhuma informação sobre ambiente testes separados do ambiente de dev (não fiz uma busca extensiva, mas andei por várias páginas da Wiki).

Eu mostrei essa issue a Yves na última aula e ele falou que os testes estão dando esse resultado mesmo.
Na tua máquina estão passando? O procedimento é diferente?
Se for, posso aproveitar e documentá-lo logo.

**Comment by embs** [comment]
Não consigo rodar o bundle. :disappointed:

**Comment by embs** [comment]
@JoaoGFarias, novidades sobre os resultados dos testes?

**Comment by JoaoGFarias** [comment]
Sim, eles podem ser encontrados no link abaixo:

https://www.dropbox.com/s/sbtlt1cwg5wd55x/rspec_results_23_11_2015.html?dl=0

* Foram 3400 testes executados:

  * 3318 passaram
  * 4 falhas
  * 78 ficaram pendentes

<img width="406" alt="screen shot 2015-11-24 at 6 07 42 pm" src="https://cloud.githubusercontent.com/assets/1585655/11380675/54f8a3fa-92d6-11e5-8823-0bfdba6be8a2.png">

**Comment by embs** [comment]
Valeu, @JoaoGFarias! Copiei e colei as specs que falham abaixo.

```
POST send_chat_message
    1) should be successful (2.19072s)

    getaddrinfo: nodename nor servname provided, or not known

    ./app/controllers/presence_controller.rb:55:in `send_chat_message'
    ./spec/controllers/presence_controller_spec.rb:208:in `block (3 levels) in '

    53
    54    begin
    55      Pusher[private_channel].trigger!('message_sent', payload)
    56      json_response = { :status => 200, :time => time }
    57    rescue Pusher::Error => e
    58# gem install syntax to get syntax highlighting

    triggers an 'message_received' pusher event (PENDING: No reason given)

    2) creates a ChatMessage (2.09749s)

    getaddrinfo: nodename nor servname provided, or not known

    ./app/controllers/presence_controller.rb:55:in `send_chat_message'
    ./spec/controllers/presence_controller_spec.rb:226:in `block (4 levels) in '
    ./spec/controllers/presence_controller_spec.rb:225:in `block (3 levels) in '

    53
    54    begin
    55      Pusher[private_channel].trigger!('message_sent', payload)
    56      json_response = { :status => 200, :time => time }
    57    rescue Pusher::Error => e
    58# gem install syntax to get syntax highlighting

    3) returns status and time (2.09946s)

    getaddrinfo: nodename nor servname provided, or not known

    ./app/controllers/presence_controller.rb:55:in `send_chat_message'
    ./spec/controllers/presence_controller_spec.rb:235:in `block (3 levels) in '

    53
    54    begin
    55      Pusher[private_channel].trigger!('message_sent', payload)
    56      json_response = { :status => 200, :time => time }
    57    rescue Pusher::Error => e
    58# gem install syntax to get syntax highlighting


GET my_wall
    1) assigns @friends (0.78066s)

    expected: not nil
         got: nil

    ./spec/controllers/users_controller_spec.rb:449:in `block (4 levels) in '

    447        @params = { :locale => "pt-BR", :id => @user.login }
    448        get :my_wall, @params
    449        assigns[var].should_not be_nil
    450      end
    451    end
    452# gem install syntax to get syntax highlighting
```

Vou modificar título e labels do issue pra tentar atrair atenção ao problema (e a necessidade de corrigí-lo).

**Comment by Bouckaert** [comment]
Resolvido por:
* Consertando os warnings do teste ( 8ac5a06e4194dfc57d5721874eb1982e446a039a ): https://github.com/Openredu/Openredu/pull/65
* Remove friends do looping ( 5740eea7ed6df5bb4ca321fe7a4e2178ad051750 ): https://github.com/Openredu/Openredu/pull/118
