### ISSUE TITLE
Possível mudança na nomeclatura de resposta de email ao se criar um disciplina

### ISSUE THREAD

**Issue by jctvEC** [Openredu/Openredu#194]
Estou fazendo um curso no Openredu, e de feedback no email recebo "Equipe Redu", se possível mudança na nomeclatura de resposta de email ao se criar um disciplina. Para Equipe Openredu. 
![image](https://user-images.githubusercontent.com/26723995/30321474-8e50751c-978c-11e7-8959-ffbf03e92dee.png)

**Comment by dan1lo** [comment]
Enviei uma modificação para o pessoal com essa solução. Agora é esperar para ver

**Comment by jctvEC** [comment]
Certo :)

**Comment by Bouckaert** [comment]
@dan1lo Obrigado pela dica.

Como estávamos trabalhando na parametrização do nome da aplicação fizemos essa alteração usando uma variável de configuração que substitui todas as ocorrências em https://github.com/Openredu/Openredu/pull/201.
