### ISSUE TITLE
UI quebrada na página de Gerenciamento do Curso 

### ISSUE THREAD

**Issue by JoaoGFarias** [Openredu/Openredu#20]
A tabela de informações do curso fica quebrada na página de Gerenciamento do Curso.

Browser: Google Chrome - Versão 46.0.2490.86
Sistema Operacional: OSX Yosemite
Ambiente: Localhost
Versão do Sistema: Commit 473b202  

Passo-a-Passo:
1 - Faça login na aplicação
2 - Crie um ambiente de ensino
3 - Siga na aba Ambientes
4 - Clique no Curso recém criado
5 - Clique em Gerenciar Curso

<img width="1274" alt="screen shot 2015-11-17 at 11 02 48 pm" src="https://cloud.githubusercontent.com/assets/1585655/11230666/736beb78-8d7f-11e5-82cf-34e1377a405e.png">

Label: bug

**Comment by leandromarquesrr** [comment]
Issue não reproduz.
