### ISSUE TITLE
Substituir MySQL por PostgreSQL

### ISSUE THREAD

**Issue by embs** [Openredu/Openredu#21]
Uma maneira de evitar o problema reportado em https://github.com/OpenRedu/OpenRedu/issues/18#issuecomment-157532160 seria substituir a ferramenta utilizada para persistência.

O [PostgreSQL](http://www.postgresql.org/) hoje é um SGBD open source amplamente utilizado e confiado por grandes organizações.

Hão de ser avaliadas questões relacionadas a:
- Compatibilidade com a base de código atual;
- Factibilidade / viabilidade de migração nas diversas instâncias do OpenRedu que estão implantadas em produção;

**Comment by Bouckaert** [comment]
@ess2, já que tu passou um tempo trabalhando nisso... Faz um PR **[WIP]** de onde tu parou que de repente a gente te ajuda ou assume a issue!

**Comment by embs** [comment]
Tome-lhe backlog! https://github.com/Openredu/Openredu/wiki/Ideias-(Backlog)#substituir-mysql-por-postgresql
