### ISSUE TITLE
Script para setup automático no ambiente Mac OS

### ISSUE THREAD

**Issue by embs** [Openredu/Openredu#22]
O script está sendo elaborado aqui: https://gist.github.com/JoaoGFarias/b00c8a527599cbdfb5c9

**Comment by embs** [comment]
Acho que o script não deve ir pra base de código do Redu. Minha sugestão é que ele seja mantido como um gist e um link pra ele seja adicionado na página de instrução de setup do projeto, na Wiki.

**Comment by embs** [comment]
O que achas, @JoaoGFarias?

**Comment by JoaoGFarias** [comment]
Como disse em #18, acho melhor manter no gist mesmo pelo menos enquanto não está completo.
Mas acho interessante adicioná-lo no repositório depois de completo; para sua manutenção não ficar restrita a mim. Como é um arquivo texto independente do sistema qualquer ajuste ser feito por algum colaborador diretamente no GitHub.

Eu parei o desenvolvimento dele porque consegui setar minha máquina e tenho o limite de tempo da cadeira de ESE, não quero arriscar ter que refazer o setup neste período. Após isso, posso continuar a trabalhar nele mais tranquilamente :)

**Comment by embs** [comment]
Tranquilo. Vou fechar este issue e avaliamos o PR quando ele for aberto, então.

**Comment by Bouckaert** [comment]
@JoaoGFarias, com o fim da disciplina ainda pretendes concluir o script? Caso contrario vou reabrir a issue para que futuros contribuidores possam dar continuidade ao trabalho.

**Comment by JoaoGFarias** [comment]
@Bouckaert, nas próximas semanas vou dar uma olhada nisso, mas acho interessante deixar a issue aberta para outros desenvolvedores, como uma melhoria.

**Comment by leandromarquesrr** [comment]
@tiagonog podemos fechar essa issue? Você vê isso como necessidade ou coisa do tipo?

**Comment by leandromarquesrr** [comment]
Issue para o voluntariado!
