### ISSUE TITLE
Utilização de labels do GitHub

### ISSUE THREAD

**Issue by embs** [Openredu/Openredu#265]
Pensei em abrir essa issue pra a gente definir junto: de quais labels a gente precisa, como cada uma delas é usada e tals. O que acham?

**Comment by embs** [comment]
Renomeei `discussão` pra `precisa-se de ajuda/questão` por conta do sentimento que a palavra discussão pode transmitir para algumas pessoas. Particularmente, estou muito acostumado a usar esse substantivo e o verbo (discutir) numa boa em contextos de trabalho mas acho que pra muita gente essas palavras podem transmitir uma ideia negativa.

Adoraria saber o que outras pessoas trabalhando no Openredu pensam sobre isso.

**Comment by heitorado** [comment]
Também não tenho problemas com 'discussão', mas acredito que a mudança é valida para alinhar bem o sentimento passado.

Talvez dê para fazer faxina em algumas labels? Me chama atenção as labels:

- backlog
- backport
- 4 labels diferentes para bug (centralizar em uma só?)
- 2 labels de colab (acho que uma delas é especifica demais, referente a um grupo de um Centro Universitário)
- voluntariado (a label de colab/boa primeira contribuição já não transmite isso?)

**Comment by embs** [comment]
> - backlog

Removi. Pra registro: só tinha um PR associado a essa label (#9).

> - backport

Removi também. Não tinha nada associado.

> - 4 labels diferentes para bug (centralizar em uma só?)

A ideia dessas labels que começam com `bug/` (ou, aliás, `qualquercoisa/`) é criar uma espécie de namespace, @heitorado. Por exemplo: o GitLab tem [a mesma ideia](https://docs.gitlab.com/ee/user/project/labels.html#scoped-labels-premium).

No caso das labels agrupadas com `bug/`:

- `bug/não consegui reproduzir`: alguém tentou reproduzir o bug mas não conseguiu, talvez já tenha sido consertado
- `bug/reproduzido`: o bug já foi "triado" e realmente acontece, então precisamos consertar
- `bug/tentar reproduzir`: ainda não foi triado, tem que ver se acontece ainda e mudar pra "reproduzido" ou "não consegui" de acordo com o resultado da tentativa

O `bug` sozinho já existia. Talvez seja útil pra quando se sabe que o issue é um bug mas não se sabe o estado dele (nem mesmo se já foi triado ou não)?

> - 2 labels de colab (acho que uma delas é especifica demais, referente a um grupo de um Centro Universitário)

Muitos issues foram criados pelo grupo da UNIFG. Acho válido taggear esses issues pra reconhecer a contribuição de maneira mais visível e até permitir algumas sumarizações (consultar o total de issues criados pelo grupo, por exemplo).

Seguindo a deia dos namespaces tb, a ideia do `colab/` é rotular tudo que disser respeito a contribuições (colaboração).

> - voluntariado (a label de colab/boa primeira contribuição já não transmite isso?)

Eu não sei qual é a ideia original dessa label "voluntariado". Será que @Bouckaert sabe?

Que tal a gente adicionar uma seção ao README com:

- Como usamos labels (esse lance de namespaces e tals, por exemplo, se for o caso de continuarmos usando a ideia mesmo)
- Como mantemos as labels: instruções de como atualizar
- Descrição de pra quê serve cada label

:question:

**Comment by heitorado** [comment]
Show! Só acho que ao invés do README, ficaria mais coeso se fosse colocado em CONTRIBUTING.

Ah, e valeu pelo esclarecimento sobre os namespaces :D

**Comment by embs** [comment]
> Show! Só acho que ao invés do README, ficaria mais coeso se fosse colocado em CONTRIBUTING.

:tada: 

Criei uma issue pra a gente botar isso no CONTRIBUTING, então, beleza? https://github.com/Openredu/Openredu/issues/279

Também fiquei com essa dúvida aqui: https://github.com/Openredu/Openredu/issues/280 Se puder dar uma ajuda lá... :pray:

**Comment by embs** [comment]
Vou fechar esse issue considerando que a gente já tem um conjunto mínimo de labels pra documentar no CONTRIBUTING através de #279, beleza?
