### ISSUE TITLE
Elementos não-responsivos na página inicial

### ISSUE THREAD

**Issue by JoaoGFarias** [Openredu/Openredu#31]
Na página inicial, antes do usuário fazer login, se a tela for re-dimensionada, alguns elementos tem comportamento não-resposivo, ficando fora de suas áreas.

Browser: Google Chrome - Versão 46.0.2490.86
Sistema Operacional: OSX Yosemite
Ambiente: Localhost
Versão do Sistema: Commit 3b17f1f

Passo-a-Passo:
1 - Acesse o OpenRedu sem estar logado;
2 - Re-dimensione a tela.

Resultado:
- Elementos não são re-dimensionados junto com a tela.

Resultado esperado:
- Todos os elementos são re-dimensionados, mantendo a interface inalterada.

Antes do re-dimensionamento:

<img width="1278" alt="screen shot 2015-12-05 at 11 09 37 am" src="https://cloud.githubusercontent.com/assets/1585655/11608201/2509a842-9b41-11e5-83a8-c0fc0d36101a.png">

Depois do re-dimensionamento:
<img width="764" alt="screen shot 2015-12-05 at 11 09 19 am" src="https://cloud.githubusercontent.com/assets/1585655/11608202/26b3ac4c-9b41-11e5-9226-8f399c8bee1b.png">

Antes do re-dimensionamento:
<img width="1277" alt="screen shot 2015-12-05 at 11 09 44 am" src="https://cloud.githubusercontent.com/assets/1585655/11608211/4fa9db26-9b41-11e5-8f1c-c583248495cc.png">

Depois do re-dimensionamento:
<img width="762" alt="screen shot 2015-12-05 at 11 09 06 am" src="https://cloud.githubusercontent.com/assets/1585655/11608212/52f9cbb0-9b41-11e5-9635-e0bbae517193.png">

Nos dois casos abaixo, foi aberta a ferramenta de inspeção de página do Chrome, verticalmente. Os elementos também não foram re-dimensionados corretamente.

<img width="1280" alt="screen shot 2015-12-05 at 11 06 16 am" src="https://cloud.githubusercontent.com/assets/1585655/11608217/7217545e-9b41-11e5-99f4-e1c75e383c95.png">
<img width="1277" alt="screen shot 2015-12-05 at 11 04 56 am" src="https://cloud.githubusercontent.com/assets/1585655/11608216/7216a6e4-9b41-11e5-821c-98e96beeb4cf.png">

Label: Bug

**Comment by Bouckaert** [comment]
Comportamento se repete em:

Browser: Iceweasel (Firefox) - Versão: 38.3.0esr-1~deb8u1
Sistema Operacional: Debian 3.16.7-ckt11-1+deb8u4
Ambiente: openredu.com
Versão do Sistema: Commit [1772b94](https://github.com/OpenRedu/OpenRedu/commit/1772b945af3353ad6577bb9cc7363df90cdbd0dc)
Resolução testada: 800x600

**Comment by embs** [comment]
Backlogged: https://github.com/Openredu/Openredu/wiki/Ideias-(Backlog)#ui-responsiva
