### ISSUE TITLE
Resposta da pergunta de segurança não é checada ao criar novo usuário

### ISSUE THREAD

**Issue by JoaoGFarias** [Openredu/Openredu#33]
Ao criar um novo usuário, o sistema não verifica a resposta dada à pergunta de segurança da gem [Humanizer](https://github.com/kiskolabs/humanizer).

Browser: Google Chrome - Versão 46.0.2490.86
Sistema Operacional: OSX Yosemite
Ambiente: Localhost
Versão do Sistema: Commit 3b17f1f

Passo-a-Passo:
1 - Acesse o OpenRedu sem estar logado;
2 - Clique no botão de criar novo usuário;
3 - Preencha corretamente os campos, exceto o campo da pergunta de segurança.

Resultado:

O usuário é criado com sucesso.

Resultado esperado:

Uma mensagem de indicando a resposta incorreta aparece e o usuário não é criado.

Criando conta com resposta incorreta

<img width="1279" alt="screen shot 2015-12-05 at 4 43 25 pm" src="https://cloud.githubusercontent.com/assets/1585655/11609821/c1aca838-9b6f-11e5-9688-86324be791a7.png">

Conta é criada com sucesso
<img width="1275" alt="screen shot 2015-12-05 at 4 43 39 pm" src="https://cloud.githubusercontent.com/assets/1585655/11609822/c1ae6858-9b6f-11e5-9f97-5a4a968d3f35.png">

Label: Bug

**Comment by leandromarquesrr** [comment]
Por questões de segurança, acredito que devemos resolver logo essa issue. @tiagonog @rafaellsma @Bouckaert

**Comment by leandromarquesrr** [comment]
@tiagonog, essa issue deve entrar  na próxima sprint?

**Comment by tiagonog** [comment]
@leandromarquesrr colocaremos.
