### ISSUE TITLE
Mensagem de erro desnecessária na página de recuperação de senha

### ISSUE THREAD

**Issue by JoaoGFarias** [Openredu/Openredu#35]
Na página de recuperação de senha, ao inserir um e-mail mal-formatado, além da mensagem "E-mail inválido", aparece outra mensagem informando o mesmo erro - sendo inconsistente com o modo de relatar erros nos outro forms (apenas com o alerta abaixo do campo incorreto).

Browser: Google Chrome - Versão 46.0.2490.86
Sistema Operacional: OSX Yosemite
Ambiente: Localhost
Versão do Sistema: Commit 3b17f1f

Passo-a-Passo:
1 - Acesse o OpenRedu sem estar logado;
2 - Clique no botão de Login;
3 - Clique no botão de Recuperação de Senha;
4 - Insira um e-mail mal-formatado.

Resultado:

Duas mensagens de erro aparecem.

<img width="961" alt="screen shot 2015-12-05 at 7 27 24 pm" src="https://cloud.githubusercontent.com/assets/1585655/11610603/e4f92ce6-9b86-11e5-95e6-6f3837745a76.png">

Resultado esperado:

Apenas a mensagem abaixo do campo deve aparecer.

Labels: Melhoria

**Comment by embs** [comment]
Backlogged: https://github.com/Openredu/Openredu/wiki/Ideias-(Backlog)#redesign
