### ISSUE TITLE
Adicionar Travis CI como serviço de integração contínua

### ISSUE THREAD

**Issue by fltiago** [OpenRedu/OpenRedu#40]
Uma dificuldade no OpenRedu atualmente é ter que rodar os testes para verificar se as contribuições não danificaram nenhuma funcionalidade já presente. Como os testes demoram, acho importante ter algum serviço de integração contínua que rode os testes a todo commit e a cada PR.

**Comment by miguelarauj1o** [comment]
@fltiago, só um admin do repo pode adicionar o Travis ao projeto, correto?

**Comment by miguelarauj1o** [comment]
> Note: You can only enable Travis CI builds for repositories you have admin access to.

https://docs.travis-ci.com/user/for-beginners

**Comment by embs** [comment]
Adicionei o [projeto ao Travis](https://travis-ci.org/OpenRedu/OpenRedu/) (sem arquivo de configuração específico do Travis, por enquanto) mas o build falha por que não consegue clonar o OpenRedu/invitable. Chequei aqui e parece estar tudo certo com esse repositório.

Alguma ideia?

**Comment by embs** [comment]
[Consegui][fail-due-to-debugger] resolver o [problema da permissão][fail-due-to-permission]. Tive que trocar todos os

    git@github.com

por

    git://github.com

Encontrei uma [explicação pra isso][so].

Pra resolver o problema com a instalação da gem debugger, fiz o que é [sugerido na documentação do Travis][travis-doc].

Agora tá dando um problema com o `config/database.yml` que, de fato, não existe.

[fail-due-to-debugger]: https://travis-ci.org/OpenRedu/OpenRedu/builds/95707981
[fail-due-to-permission]: https://travis-ci.org/OpenRedu/OpenRedu/builds/95707174
[so]: http://stackoverflow.com/questions/21532367/why-does-git-works-but-git-does-not
[travis-doc]: https://docs.travis-ci.com/user/common-build-problems/#Ruby%3A-Installing-the-debugger_ruby-core-source-library-fails

**Comment by embs** [comment]
[Agora foi][foi]! \o/

Vou esperar um pouco antes de fazer o merge de #43 e abrir um PR pra resolução deste issue.

[foi]: https://travis-ci.org/OpenRedu/OpenRedu/builds/95795875
