### ISSUE TITLE
Docker para OpenRedu

### ISSUE THREAD

**Issue by marcus2vinicius** [Openredu/Openredu#52]
Existe algum projeto para criação do Docker para OpenRedu, pois facilitaria bastante o start para se desenvolver?

**Comment by fltiago** [comment]
@marcus2vinicius existe não, mas seria incrível ter. Sugiro até usar algum tipo de abstração, tipo o [kubernetes](http://kubernetes.io/) ou algo parecido.

O que se tem é um deploy em andamento usando o [capistrano](https://github.com/capistrano/capistrano) e [rubber](https://github.com/rubber/rubber) para máquinas locais.

**Comment by Bouckaert** [comment]
@marcus2vinicius para iniciar rapidamente o desenvolvimento disponibilizamos uma box já configurada com o Openredu no vagrant:

https://github.com/OpenRedu/OpenRedu/wiki/Openredu-Vagrant

**Comment by lucianoskyline** [comment]
Estou tentando configurar a box, porem quando executo "vagrant up" me retorna esse erro:

An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

Couldn't open file /Users/lucianoskyline/OpenR/OpenR

**Comment by thunderboy** [comment]
Também temos uma VM em Virtual Box e VMware:
http://forum.openredu.com/t/maquina-virtual-com-instalacao-padrao-do-openredu/67

**Comment by Bouckaert** [comment]
Como não existe previsão para adoção do docker e as três alternativas para setup do ambiente([local](https://github.com/Openredu/Openredu/wiki/OpenRedu-Setup-(Ubuntu)), vagrant e VM) foram apresentadas, estou fechando essa issue.
