### ISSUE TITLE
Desenvolvimento de plugins

### ISSUE THREAD

**Issue by lucianoskyline** [Openredu/Openredu#53]
Olá, existe alguma documentação para criação de plugins?

**Comment by Bouckaert** [comment]
Olá @lucianoskyline,

O Openredu possui uma arquitetura de micro-serviços que se comunicam por meio de uma API-REST cuja documentação pode ser encontrada em [developers.openredu.com](http://developers.openredu.com/)

Qual funcionalidade você deseja implementar?

**Comment by lucianoskyline** [comment]
Obrigado, eu havia encontrado esse link porem não estava conseguindo acessar os dominios do openredu neste final de semana. Gostaria de fazer uma captura das ações dos usuários na plataforma (postagens que o usuario criou, editou), é possivel isso?

**Comment by Bouckaert** [comment]
@lucianoskyline Você conseguiu usar a API? Precisa de ajuda? Posso fechar a issue?
