### ISSUE TITLE
Erro na reprodução de videos do youtube

### ISSUE THREAD

**Issue by minhaqui** [Openredu/Openredu#54]
Quando um video é carregado pelo youtube na plataforma do Openredu, acontece o erro #2035 do JWplayer referente ao carregamento de videos do youtube que antigamente era feito com Flash e agora é feito com HTML5.
É provavel que uma atualização do plugin resolva o problema, como descrito na thread
http://stackoverflow.com/questions/35223433/jwplayer6-giving-error-2035-on-firefox-for-youtube-videos

![img-20160521-wa0001](https://cloud.githubusercontent.com/assets/9600226/15451051/3362aef0-1f87-11e6-8480-cf07dfe7830d.jpg)

![img-20160521-wa0002](https://cloud.githubusercontent.com/assets/9600226/15451052/3bdf60dc-1f87-11e6-9379-fa473946fe51.jpg)

**Comment by Bouckaert** [comment]
Resolvido por #131
