### ISSUE TITLE
Bug botão "Comentar" em página de exercício

### ISSUE THREAD

**Issue by matheusfelic** [Openredu/Openredu#58]
A função do botão "Comentar" não está presente tanto na página de apresentação do exercício quanto na de realização. Quando o botão é clicado nada acontece.

**Comment by Bouckaert** [comment]
![issue-58](https://cloud.githubusercontent.com/assets/7050977/22943092/ed6bc46e-f2ca-11e6-9d89-dd9a53111e06.png)

**Comment by Bouckaert** [comment]
@jeffersonalexsilva @alexodrosgomes Apesar da existência do botão, essa funcionalidade não está implementada para atividades do tipo exercicio. É realmente permitido ao usuário realizar um comentário no exercício? Ou seria melhor remover o botão?

**Comment by jeffersonalexsilva** [comment]
@Bouckaert acredito que o comentário no exercício foi pensado ao mesmo tempo de um comentário em material (mini fórum), mas eu não vejo muito sentido o comentário em um exercício que não seja o do próprio professor/tutor do curso. Veja se há a possibilidade desse botão aparecer apenas para o perfil de professor.
Caso dê, acredito que o comentário do exercício deverá ficar visível para todos os membros do painel/curso.
Se isso ficar complexo para o momento, podemos discutir isso em outra sprint e excluir esse botão por enquanto.

**Comment by rafaellsma** [comment]
@Bouckaert @jeffersonalexsilva Implementar a parte de quem pode ou não comentar seria complexo, então, por agora, eu removi o botão das paginas de exercicio. https://github.com/Openredu/Openredu/pull/138
