### ISSUE TITLE
Erro no convite de membros em openredu.com

### ISSUE THREAD

**Issue by alexodrosgomes** [Openredu/Openredu#59]
Quando tentamos acessar a função de convite de membros ocorre um erro:
http://openredu.com/espacos/13/admin_membros

**Comment by Bouckaert** [comment]
@alexodrosgomes Não consegui reproduzir esse bug, você pode fornecer mais informações?

**Comment by Bouckaert** [comment]
Verificar se existe relação com #70

**Comment by rafaellsma** [comment]
Acredito que sejam errors distintos, pois são relações diferentes um está relacionado com os convites de amizade e outro com o para um curso.

**Comment by leandromarquesrr** [comment]
@Bouckaert @rafaellsma @tiagonog logado, acessa esse endereço http://openredu.com/raia-drogasil/cursos/marketing, em seguida, clica na imagem openredu (canto superior esquerdo) > Ops! Algo inesperado aconteceu. ERRO500 

INVESTIGAR!

**Comment by rafaellsma** [comment]
@Bouckaert @leandromarquesrr @tiagonog Aparentemente, depois que você participa desse curso, sua home quebra.

**Comment by rafaellsma** [comment]
O problema está relacionado a um usuário que por alguma razão sumiu do banco de dados, e não é possível rastrear pois não temos o log da criação desse ambiente.

Esse id de usuário 211 não existe.
<img width="1280" alt="captura de tela 2017-07-18 as 08 20 50" src="https://user-images.githubusercontent.com/13156606/28314811-5ca4b2d8-6b92-11e7-913f-750b97edc69d.png">

@Bouckaert temos que ver como resolver isso(Maneira rápida: Deletar esse ambiente, já que não está sendo usado e não é possível rastrear essa inconsistência) e também testar se um usuário for deletado(Da maneira correta. Config>Excluir conta...) ele vai ser totalmente limpo do banco(Environment, courses, friendships, logs e etc).

**Comment by rafaellsma** [comment]
O problema está relacionado a um usuário que por alguma razão sumiu do banco de dados, e não é possível rastrear pois não temos o log da criação desse ambiente.

Esse id de usuário 56 não existe.
<img width="1280" alt="captura de tela 2017-07-18 as 09 00 42" src="https://user-images.githubusercontent.com/13156606/28316116-d9e2a516-6b97-11e7-9910-b2efa67b39c1.png">


@Bouckaert temos que ver como resolver isso(Maneira rápida: Deletar esse ambiente, já que não está sendo usado e não é possível rastrear essa inconsistência) e também testar se um usuário for deletado(Da maneira correta. Config>Excluir conta...) ele vai ser totalmente limpo do banco(Environment, courses, friendships, logs e etc).

**Comment by leandromarquesrr** [comment]
@rafaellsma isso também deve ter relação com isso https://github.com/Openredu/Openredu/issues/97

**Comment by tiagonog** [comment]
@leandromarquesrr achamos que não tem relação com essa issue. Como @rafaellsma disse, a exclusão de conta pelo fluxo normal evita que problemas como esse aconteçam.
