### ISSUE TITLE
Testes do mailers com warnings

### ISSUE THREAD

**Issue by rafaellsma** [Openredu/Openredu#64]
Ao rodar os testes levanta os warnings abaixo:
<img width="1153" alt="captura de tela 2017-01-12 as 10 03 59" src="https://cloud.githubusercontent.com/assets/13156606/21890863/798a7de6-d8ae-11e6-84c5-318fe822d379.png">

**Comment by Bouckaert** [comment]
@rafaellsma Essa issue já havia sido aberta por @embs em #45
