### ISSUE TITLE
Todos podem ver os uploads feitos por outras pessoas no CKEditor

### ISSUE THREAD

**Issue by rafaellsma** [Openredu/Openredu#68]
https://github.com/redu/redu/issues/29

**Comment by rafaellsma** [comment]
Visto que essa parte de importar e pegar a imgem é feito com flash, eu desativei, ficando a opção de colocar o link de uma imagem.

**Comment by Bouckaert** [comment]
@rafaellsma Tá vendo que assim não fecha, você tem que colocar o resolve #68 na msg do commit!

**Comment by Bouckaert** [comment]
@leandromarquesrr, lembras se essa feature da sprint 9 foi testada?

Acabei de  evidenciá-la na openredu.ufpe.br:
![captura de tela_2017-09-14_18-11-43](https://user-images.githubusercontent.com/7050977/30456304-6a2e947c-9979-11e7-9f29-2d295784004b.png)

Confirmei que o código esta com as alterações desse merge:
```

[$] cat -n /mnt/openredu-staging/current/vendor/assets/javascripts/ckeditor/config.js 
    ...
    ...
    ...
    45	  config.toolbar = 'Easy';
    46	
    47	  config.toolbar_Easy =
    48	    [
    49	    ['Preview','-','Templates'],
    50	    ['Cut','Copy','Paste','PasteText','PasteFromWord'],
    51	    ['Undo','Redo','-','Find','-','SelectAll','RemoveFormat'],
    52	    ['Bold','Italic','Underline','Strike','-','Subscript','Superscript'],
    53	    ['NumberedList','BulletedList','-','Outdent','Indent','Blockquote'],
    54	    ['JustifyLeft','JustifyCenter','JustifyRight','JustifyBlock'],
    55	    ['Link','Unlink','Anchor'],
    56	    ['Image','Table','HorizontalRule','Smiley','SpecialChar','PageBreak'],
    ...
    ...
    ...
    62	};

```

Talvez o problema esteja na compilação dos assets.

@rafaellsma achas melhor reabrir a issue ou criar outra?

**Comment by Inovaula** [comment]
@Bouckaert , testei e não passou! Daí @rafaellsma disse que não passou pq ainda não estava finalizada implementação.
