### ISSUE TITLE
Confusão na thread de uma mensagem enviada

### ISSUE THREAD

**Issue by rafaellsma** [Openredu/Openredu#74]
https://github.com/redu/redu/issues/1334

**Comment by Bouckaert** [comment]
@jeffersonalexsilva tens alguma sugestão para o tratamento dessa issue?

**Comment by jeffersonalexsilva** [comment]
@Bouckaert acredito que uma solução mais simples e rápida seja simplificar o que aparece. No que vejo a imagem e nome da pessoa que aparece é da destinatária. Então o erro é basicamente de design da informação.
Veja no anexo uma solução para mensagens enviadas e recebidas
![mensagem-recebida](https://cloud.githubusercontent.com/assets/22921518/26373047/7e3172c0-3fd6-11e7-8e88-59f7aea38409.jpg)
![mensagens-enviadas](https://cloud.githubusercontent.com/assets/22921518/26373048/7e363dc8-3fd6-11e7-9bf8-7af3be99ad36.jpg)

**Comment by tiagonog** [comment]
@leandromarquesrr lembra de verificar se a usabilidade desta implementação está boa quando a atualização estiver no ar.
