### ISSUE TITLE
Aumentar limite de caracteres para a criação de resposta/status.

### ISSUE THREAD

**Issue by rafaellsma** [Openredu/Openredu#83]
https://github.com/redu/redu/issues/1463

**Comment by rafaellsma** [comment]
Alterei o limite para 1600 a partir de uma conversa com @Bouckaert https://github.com/Openredu/Openredu/pull/139, pois deixar sem limites pode trazer problemas de perfomance e segurança, os quais ainda precisamos pesquisar mais.

**Comment by Bouckaert** [comment]
Resolvido em #139

**Comment by Bouckaert** [comment]
Estou excluindo o branch https://github.com/Openredu/Openredu/tree/issue-1463 que tratava da mesma implementação https://github.com/Openredu/Openredu/commit/c2dd92a686f3ea935faa71b657e41dfb6540c561.
