### ISSUE TITLE
Funcionalidade de Integração com o Inovaula

### ISSUE THREAD

**Issue by embs** [Openredu/Openredu#9]
Os pull requests #3 #4 #5 #6 e #7 fazem modificações que dizem respeito ─ ao menos em parte ─ à funcionalidade de integração com o Inovaula. No entanto, nenhum deles especifica quais são as pretensões futuras para essa funcionalidade.

Estou criando este issue para discussões relacionadas.

Alguém pode, introdutoriamente, explicar a macro-ideia da integração Redu-Inovaula?

**Comment by duduRodrigues** [comment]
Olá embs, eu tenho um grupo com mais 2 pessoas e nós estamos responsáveis pela integração dos dois sistemas (OpenRedu e Inovaula). A nossa ideia é fazer com que seja possível linkar planos de aula do Inovaula direto nas disciplinas do OpenRedu. Por exemplo, se um professor criar uma disciplina "Grandezas e Unidades", ele poderá adicionar um plano de aula do Inovaula a essa disciplina, e assim os alunos poderão ver esse plano para se "guiar" durante os estudos. Acho que não está muito bem explicado, qualquer coisa é só perguntar. Valeu!

**Comment by embs** [comment]
@duduRodrigues comentou sobre a funcionalidade:

> Olá @embs, eu tenho um grupo com mais 2 pessoas (henvic é do meu grupo) e nós estamos responsáveis pela integração dos dois sistemas (OpenRedu e Inovaula). A nossa idéia é fazer com que seja possível linkar planos de aula do Inovaula direto nas disciplinas do OpenRedu. Por exemplo, se um professor criar uma disciplina "Grandezas e Unidades", ele poderá adicionar um plano de aula do Inovaula a essa disciplina, e assim os alunos poderão ver esse plano para se "guiar" durante os estudos. Acho que não está muito bem explicado, qualquer coisa é só perguntar.

**Comment by embs** [comment]
Estou movendo essa ideia pro [backlog](https://github.com/Openredu/Openredu/wiki/Ideias-(Backlog)#integração-com-o-inovaula) pra manter os issues focados no que estamos fazendo ou precisamos fazer mais imediatamente.

Por favor, sinta-se à vontade para reabrir este issue se quiser trabalhar nele (começando por uma proposta, nesse caso específico, eu acho).
