### ISSUE TITLE
Não é possível buscar algo diferente do que é mostrado na busca instantânea

### ISSUE THREAD

**Issue by rafaellsma** [Openredu/Openredu#92]
https://github.com/redu/redu/issues/1574

**Comment by Bouckaert** [comment]
O comportamento esperado da busca instantânea é retornar apenas os primeiros dois resultados, conforme configuração no config/application.rb:

`config.instant_search_preview_results_per_page = 2`

@leandromarquesrr confirma se podemos fechar essa issue, pfv!

**Comment by leandromarquesrr** [comment]
@Bouckaert , acho que foi alterado, pois agora está aparecendo 5. Confirma se foi alterado mesmo. A resposta com 5 está bem melhor. Confirma 5.

**Comment by tiagonog** [comment]
@leandromarquesrr , achamos que você está confundindo o preview da busca instantânea com a  busca instantânea em si. O preview é o que aparece na barra e não foi alterado, exibe apenas 2.
